//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CapsuleSorter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAPSULESORTER_DIALOG        102
#define IDS_TMPLCFG_TITLE               102
#define IDS_CAMERACFG_TITLE             103
#define IDS_CTRLCARDCFG_TITLE           104
#define IDS_OPENDLG_TITLE               105
#define IDS_SAVEDLG_TITLE               106
#define IDS_SAVECFGFILE_TITLE           107
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     130
#define IDI_LT_RED                      139
#define IDI_LT_YELLOW                   141
#define IDI_LT_GREEN                    142
#define IDI_DK_GREEN                    143
#define IDI_DK_YELLOW                   144
#define IDI_DK_RED                      145
#define IDI_ICON                        147
#define IDI_ICON1                       148
#define IDI_ICON2                       149
#define IDD_SELECT_TEMP_MODE            149
#define IDI_ICON3                       150
#define IDI_ICON4                       152
#define IDD_CAMERA_CONFIG               154
#define IDD_SOFTWARE_CONFIG             155
#define IDD_CTRLBOARD_CONFIG            158
#define IDD_HARDWARE_CONFIG             160
#define IDD_KEYBOARD                    165
#define IDD_VERTIFY_DIALOG              166
#define IDD_SPECIFY_CAPSUAL_CFG         176
#define IDD_DLG_PATHSELECT              177
#define IDC_LoadImage                   1000
#define IDC_GrabImage                   1001
#define IDC_CAMCAPTURE                  1001
#define IDC_RawImgRect                  1002
#define IDC_CAMFREEZE                   1002
#define IDC_HdlImgRect                  1003
#define IDC_COLOR_RECT                  1004
#define IDC_FreezeImg                   1005
#define IDC_COLOR_RECT2                 1005
#define IDC_MONO_RECT                   1005
#define IDC_RawImgRect2                 1006
#define IDC_GenieToGenie                1006
#define IDC_HdlImgRect2                 1007
#define IDC_ProciToProci                1007
#define IDC_TestResult                  1008
#define IDC_GenieToProci                1008
#define IDC_TEMP_LIST                   1008
#define IDC_AllCount                    1009
#define IDC_ProciToGenie                1009
#define IDC_ClearCount                  1010
#define IDC_ROIStartX                   1010
#define IDC_ROIStartY                   1011
#define IDC_ROIWidth                    1012
#define IDC_PictureFrame                1013
#define IDC_ROIHeight                   1013
#define IDC_TestTarget                  1014
#define IDC_ExpTime                     1014
#define IDC_ROIStartX2                  1015
#define IDC_MONO_ROI_STARTX             1015
#define IDC_SaveImage                   1016
#define IDC_ROIStartY2                  1016
#define IDC_MONO_ROI_STARTY             1016
#define IDC_SaveMultImg                 1017
#define IDC_ROIWidth2                   1017
#define IDC_MONO_ROI_WIDTH              1017
#define IDC_LoadMultImg                 1018
#define IDC_ROIHeight2                  1018
#define IDC_MONO_ROI_HEIGHT             1018
#define IDC_IsSim                       1019
#define IDC_ExpTime2                    1019
#define IDC_MONO_EXPTIME                1019
#define IDC_END_COMTEST                 1020
#define IDC_START_COMTEST               1021
#define IDC_BadCount                    1022
#define IDC_SOFTCFG                     1024
#define IDC_HARDCFG                     1025
#define IDC_LIGHT                       1026
#define IDC_MSCOMM1                     1028
#define IDC_Gain                        1028
#define IDC_GREEN                       1029
#define IDC_Gain2                       1029
#define IDC_MONO_GAIN                   1029
#define IDC_YELLOW                      1030
#define IDC_RED                         1031
#define IDC_MADE_NEW_TEMP               1032
#define IDC_RELOAD_TEMP                 1033
#define IDC_WhiteRedVal                 1034
#define IDC_WhiteBlueVal                1035
#define IDC_SET_COLORCAM                1036
#define IDC_CamSelect                   1037
#define IDC_GET_COLORCAM                1038
#define IDC_SET_MONOCAM                 1039
#define IDC_GET_MONOCAM                 1040
#define IDC_SENSOR_SHIELD_EDT           1041
#define IDC_CAM1_DELAY                  1042
#define IDC_COMBO1                      1043
#define IDC_SENSOR_COMB                 1043
#define IDC_CAM1_HOLD                   1044
#define IDC_LIGHT1_DELAY                1045
#define IDC_LIGHT1_HOLD                 1046
#define IDC_COMBO6                      1047
#define IDC_CAM_COMB                    1047
#define IDC_SET_CONTROLBOARD            1049
#define IDC_SET_TIMEORDER               1049
#define IDC_SENSOR_SEL                  1053
#define IDC_SENSOR_SHIELD               1054
#define IDC_SENSOR_SEL2                 1055
#define IDC_COMBO2                      1057
#define IDC_LAMP_COMB                   1057
#define IDC_BUTTON1                     1058
#define IDC_TEST_LAMP                   1058
#define IDC_BTN_ONE                     1058
#define IDC_SOFTKEYBD                   1058
#define IDC_CamSoftKeyBD                1058
#define IDC_CfgSoftKeyBD                1058
#define IDC_SaveState                   1058
#define IDC_BTN_DEF                     1058
#define IDC_COMBO3                      1059
#define IDC_NEXT_FRAM                   1059
#define IDC_WORKMODE                    1059
#define IDC_BUTTON2                     1060
#define IDC_SET_COMPLEX                 1060
#define IDC_BTN_TWO                     1060
#define IDC_CapSoftKeyBD                1060
#define IDC_LoadConfigFile              1060
#define IDC_BTN_SELECT                  1060
#define IDC_COMBO4                      1061
#define IDC_SAVE_IMAGE                  1061
#define IDC_WATCH_DOG_MODE              1061
#define IDC_COMPLETE                    1061
#define IDC_COMBO5                      1062
#define IDC_LOAD_TEMPLATE               1062
#define IDC_VALVE_COMB                  1062
#define IDC_EDIT1                       1063
#define IDC_VALVE_HOLD                  1063
#define IDC_BakeSeries                  1063
#define IDC_SPECIFY_CAPSUAL             1063
#define IDC_RADIUS                      1063
#define IDC_COMBO7                      1064
#define IDC_CAMINTER1                   1064
#define IDC_EDT_MINBOXWIDTH             1064
#define IDC_COMBO8                      1065
#define IDC_CAMINTER2                   1065
#define IDC_EDIT2                       1066
#define IDC_CAM_VALVE_DISTANCE1         1066
#define IDC_SizeChange                  1066
#define IDC_SizeChange1                 1066
#define IDC_RECORD                      1066
#define IDC_EDIT3                       1067
#define IDC_CAM_VALVE_DISTANCE2         1067
#define IDC_Hue1Change                  1067
#define IDC_BUTTON3                     1068
#define IDC_SET_SPACE                   1068
#define IDC_BTN_THREE                   1068
#define IDC_SaveConfigFile              1068
#define IDC_SizeChange2                 1068
#define IDC_EDIT4                       1069
#define IDC_CAPSUAL_INTERVAL            1069
#define IDC_Hue2Change                  1069
#define IDC_EDIT5                       1070
#define IDC_AXIS_RADIUS                 1070
#define IDC_MonoMaxVal                  1070
#define IDC_MaxBright                   1070
#define IDC_EDIT6                       1071
#define IDC_CODE_PRECISION              1071
#define IDC_ColorMaxVal                 1071
#define IDC_EDIT7                       1072
#define IDC_PULSE_INTERVAL              1072
#define IDC_EDIT8                       1073
#define IDC_CODE_ADJUST                 1073
#define IDC_BUTTON4                     1074
#define IDC_SET_OTHER                   1074
#define IDC_BTN_FOUR                    1074
#define IDC_BUTTON5                     1075
#define IDC_TEST_VALVE                  1075
#define IDC_BTN_FIVE                    1075
#define IDC_COMBO9                      1076
#define IDC_VALVE_INDEX                 1076
#define IDC_BUTTON6                     1077
#define IDC_SET_VALUE                   1077
#define IDC_BTN_SIX                     1077
#define IDC_BUTTON7                     1078
#define IDC_READ_CURRENT                1078
#define IDC_BTN_SEVEN                   1078
#define IDC_CAM_CFG                     1079
#define IDC_CONTROLBOARD_CFG            1080
#define IDC_CVDISPLAYCTRL1              1081
#define IDC_CVDISPLAY                   1081
#define IDC_LOAD_IMAGE                  1082
#define IDC_DROP_RESULT                 1083
#define IDC_EDIT9                       1084
#define IDC_VALVE_DELAY                 1084
#define IDC_TargetTitle                 1085
#define IDC_ResultTitle                 1086
#define IDC_BTN_EIGHT                   1087
#define IDC_BTN_NINE                    1088
#define IDC_BTN_ZERO                    1089
#define IDC_BTN_DOT                     1090
#define IDC_BTN_BACK                    1091
#define IDC_BTN_LEFT                    1092
#define IDC_BTN_RIGHT                   1093
#define IDC_BTN_ESC                     1094
#define IDC_TestGroup                   1095
#define IDC_CtrlSoftKeyBD               1097
#define IDC_FrontLightEnable            1098
#define IDC_ValveEnable                 1099
#define IDC_OnlyErrEnable               1100
#define IDC_TRANSPARENT                 1100
#define IDC_VERTIFYMSG                  1101
#define IDC_WrongSave                   1101
#define IDC_SPIN1                       1102
#define IDC_SaveAll                     1104
#define IDC_CHECK1                      1107
#define IDC_PROFILE                     1107
#define IDC_SCROLLBAR1                  1108
#define IDC_SCL_RADIUS                  1108
#define IDC_SCRL_MINBOXWIDTH            1109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
